"""add_version_column

Revision ID: 49643cd92e72
Revises: 4375d3cb5493
Create Date: 2026-02-05 16:27:01.500783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49643cd92e72'
down_revision: Union[str, None] = '4375d3cb5493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'version')
    # ### end Alembic commands ###
